### get all the loan item 
get http://localhost:5000/api/loanitem?filter={"transaction_id":"d6","item_id":""}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF0cmFtQGdtYWlsLmNvcG0iLCJpYXQiOjE2MTg1MTI0MzUsImV4cCI6MTYxODUxNjAzNX0.2PxKI7bJZwm-ZLUXwqk-Jy2xIunvlTUjGC8vOfZIJe4
### 
get http://localhost:5000/api/loanitem?filter={"quantity":1, "item_id":0}
### get one loan item 
get http://localhost:5000/api/loanitem/4

###
get http://localhost:5000/api/loanitem/many?filter={"id":[5,6]}


### delete one loan item 

delete http://localhost:5000/api/loanitem/one/6

### delete many loanitems
delete http://localhost:5000/api/loanitem/many?filter={"id":[8,9]}
### create one loan item with quantity and item_id and trans_id 
post http://localhost:5000/api/loanitem
Content-Type: application/json

{
    "transaction_id": "1adfc6ff-8ad7-466b-8c5d-b3cfb266fcba",
    "item_id":5,
    "quantity":10
}

### edit the quantity in the loan item 
put http://localhost:5000/api/loanitem/1
Content-Type: application/json

{
    "quantity":10, 
    "is_due": 0 
}


### 

post http://localhost:5000/api/loanitem
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF0cmFtQGdtYWlsLmNvcG0iLCJpYXQiOjE2MTkzMjE2NDIsImV4cCI6MTYxOTMyNTI0Mn0.2B-Q3yYpVno09R7EyiOhNTJmdE_FzvQaPR7VUCHXgR0

{
    "transaction_id": "1adfc6ff-8ad7-466b-8c5d-b3cfb266fcba",
    "item_id":6
}