### get all the loan item 
get http://localhost:5000/api/loanitem


### get one loan item 
get http://localhost:3000/loanitem/1adfc6ff-8ad7-466b-8c5d-b3cfb266fcba/1


### delete one loan item 

delete http://localhost:3000/loanitem/1adfc6ff-8ad7-466b-8c5d-b3cfb266fcba/1


### create one loan item with quantity and item_id and trans_id 
post http://localhost:3000/loanitem
Content-Type: application/json

{
    "trans_id": "1adfc6ff-8ad7-466b-8c5d-b3cfb266fcba",
    "item_id":5,
    "quantity":3
}

### edit the quantity in the loan item 
put http://localhost:3000/loanitem/1adfc6ff-8ad7-466b-8c5d-b3cfb266fcba/5
Content-Type: application/json

{
    "quantity":5
}
