### getOne 
GET http://localhost:5000/api/transactions/one/1adfc6ff-8ad7-466b-8c5d-b3cfb266fcba
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF0cmFtQGdtYWlsLmNvcG0iLCJpYXQiOjE2MTg0MzExMDYsImV4cCI6MTYxODQzNDcwNn0.DJPrKTwVKEXX0s1DpOG3hneuU96n-LFDb6d8qGvtIU

###  getList
GET http://localhost:5000/api/transactions?filter={}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF0cmFtQGdtYWlsLmNvcG0iLCJpYXQiOjE2MTg0MzExMDYsImV4cCI6MTYxODQzNDcwNn0.DJPrKTwVKEXX0s1DpOG3hneuU96n-LFDb6d8qGvtIUE
### get transaction for a user 
GET http://localhost:5000/api/transactions?filter={"user_id":2} 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF0cmFtQGdtYWlsLmNvcG0iLCJpYXQiOjE2MTg0NTI5MTQsImV4cCI6MTYxODQ1NjUxNH0.8SAtJQ1HDP9gTjbYtPXk6hFTpetwxAnW7TFx0HpQkvc

### getMany 
GET http://localhost:5000/api/transactions/many?filter={"id":["a0884e0d-1dd6-49ed-8e1e-bb2354d65df9","752ca4cf-c923-4eac-ae67-2c43f7f0b5e9"]}

###  update one 


### create new post for user id = 1  
POST http://localhost:5000/api/transactions 
Content-Type: application/json

{
    "user_id": 1
}

### remove one 
DELETE http://localhost:5000/api/transactions/0855c22b-a84f-447a-9023-5ecdb287b8a9


### remove many baseon the filters 

DELETE http://localhost:5000/api/transactions/many?filter={"id":["d8098b78-08bc-4f9b-9956-d670030c8bee"]}


###
GET http://localhost:3000/api/transactions/view_all_items/1adfc6ff-8ad7-466b-8c5d-b3cfb266fcba



### 
put http://localhost:5000/api/transactions/1adfc6ff-8ad7-466b-8c5d-b3cfb266fcba
Content-Type: application/json

{
    "user_id":1, 
    "is_commit":0 
}
### 
get http://localhost:5000/api/reports/transactions
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF0cmFtQGdtYWlsLmNvcG0iLCJpYXQiOjE2MTg0NTI5MTQsImV4cCI6MTYxODQ1NjUxNH0.8SAtJQ1HDP9gTjbYtPXk6hFTpetwxAnW7TFx0HpQkvc

{
    "startdate":"2021-04-01", 
    "enddate":"2021-04-30" 
}
