# Build Pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Buildling!
  displayName: 'Build > Deploy'

- task: SSH@0
  inputs:
    sshEndpoint: 'DO'
    runOptions: 'commands'
    commands: 'cd /home/api/Backend/uhlib-api/;pm2 stop index.js'
    readyTimeout: '20000'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'DO'
    contents: '**'
    targetFolder: '/home/api/'
    readyTimeout: '20000'

- task: SSH@0
  inputs:
    sshEndpoint: 'DO'
    runOptions: 'commands'
    commands: 'cd /home/api/Backend/uhlib-api/;npm i; pm2 start index.js'
    readyTimeout: '20000'